# Generated by Django 4.1.6 on 2023-08-02 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inupgroapp', '0002_schoolsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.BigIntegerField()),
                ('date_of_birth', models.DateField()),
                ('teacher_dropdown', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
