# Generated by Django 4.1.6 on 2023-08-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0004_collegesignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='host_UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_Or_Phone', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('category', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('schoolpage', 'School Page')], max_length=20)),
                ('education_type', models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('institute', 'Institute')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='collegesignup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='institutesignup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schoolsignup',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSignUp',
        ),
        migrations.CreateModel(
            name='SchoolPage',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inupgroapp.userprofile')),
                ('founder_name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
            ],
            bases=('inupgroapp.userprofile',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inupgroapp.userprofile')),
                ('college_name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
            ],
            bases=('inupgroapp.userprofile',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inupgroapp.userprofile')),
                ('school_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
            bases=('inupgroapp.userprofile',),
        ),
        migrations.DeleteModel(
            name='CollegeSignUp',
        ),
        migrations.DeleteModel(
            name='InstituteSignUp',
        ),
        migrations.DeleteModel(
            name='SchoolSignUp',
        ),
    ]
