# Generated by Django 4.1.6 on 2023-08-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0005_host_userdata_userprofile_remove_collegesignup_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_userdata',
            name='email_Or_Phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
