# Generated by Django 4.1.6 on 2023-08-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0008_rename_email_or_phone_host_userdata_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='host_userdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host_userdata',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host_userdata',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
