# Generated by Django 4.1.6 on 2023-08-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0009_alter_host_userdata_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collegename', models.CharField(max_length=30)),
                ('CollegeHeading', models.TextField()),
                ('CollegeDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institutionname', models.CharField(max_length=30)),
                ('InstitutionHeading', models.TextField()),
                ('InstitutionDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ourpartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartnersName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schoolname', models.CharField(max_length=30)),
                ('SchoolHeading', models.TextField()),
                ('SchoolDescription', models.TextField()),
            ],
        ),
    ]
