# Generated by Django 4.1.6 on 2023-08-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0010_collegedetails_institutiondetails_ourpartners_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerStrategiest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('fieldname', models.CharField(max_length=50)),
                ('officelocation', models.CharField(max_length=50)),
                ('minimumqualification', models.CharField(max_length=50)),
                ('experiencelavel', models.CharField(max_length=50)),
                ('vacancylocation', models.CharField(max_length=30)),
                ('jobdescription', models.TextField(max_length=100)),
                ('technicalrequirement', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_items/')),
                ('achievements_and_certificates', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('abouts', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
