# Generated by Django 4.1.6 on 2023-08-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0011_careerstrategiest_teacherportfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus_descriptions', models.TextField(max_length=1000)),
                ('photos', models.ImageField(max_length=50, upload_to='')),
            ],
        ),
    ]
