# Generated by Django 4.1.6 on 2023-08-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0012_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCounselors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeAndCareerCounselors', models.TextField(max_length=50)),
                ('CollegeVineCounselors', models.TextField(max_length=1000)),
            ],
        ),
    ]
