# Generated by Django 4.1.6 on 2023-08-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0013_careercounselors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careercounselors',
            name='CollegeAndCareerCounselors',
            field=models.TextField(max_length=500),
        ),
    ]
