# Generated by Django 4.1.6 on 2023-08-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0014_alter_careercounselors_collegeandcareercounselors'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorportfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_items/')),
                ('full_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('achievements_and_certificates', models.TextField(blank=True, null=True)),
                ('field_of_expertise', models.CharField(max_length=50)),
                ('connectedschool', models.IntegerField()),
                ('connectedcollege', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('abouts', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherPortfolioItem',
        ),
    ]
