# Generated by Django 4.1.6 on 2023-08-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0016_clubdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdetails',
            name='founded_year',
            field=models.IntegerField(max_length=4),
        ),
    ]
