# Generated by Django 4.1.6 on 2023-08-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0017_alter_clubdetails_founded_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdetails',
            name='aboutus',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='clubdetails',
            name='club_details',
            field=models.TextField(max_length=10000),
        ),
    ]
