# Generated by Django 4.1.6 on 2023-08-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inupgroapp', '0018_alter_clubdetails_aboutus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdetails',
            name='photos',
            field=models.ImageField(default=1, upload_to='club_photogallery/'),
            preserve_default=False,
        ),
    ]
